go2_patrol:
  ros__parameters:
    # 初始位姿（地图坐标系：x,y,yaw（弧度））
    initial_point: [0.0, 0.0, 0.0]
    # 目标航点（每3个为一组：x,y,yaw（弧度），支持N个航点）
    # 示例：4个航点，形成矩形巡逻路线
    target_points:
      [
        1.6457520723342896, -0.009389510378241539, -0.005340576171875,    # 航点1：x=2, y=0, 朝向0°
        1.7333511114120483, -2.0111658573150635, -0.001434326171875,   # 航点2：x=2, y=2, 朝向90°（π/2弧度）
        0.6945875883102417, -2.0049068927764893, -0.005340576171875,   # 航点3：x=0, y=2, 朝向180°（π弧度）
      ]